[package]
name = "oc-voice"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Speech: Groq Whisper"

[dependencies]
oc-time.workspace = true
oc-timeline.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["process", "time"] }
tracing.workspace = true
